[package]
name = "rust_opengl"
version = "0.1.0"
authors = ["0918nobita <nobita.0918@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.33.0"
gl = "0.14.0"
cgmath = "0.17.0"
c_str_macro = "1.0.2"
